#include:
#  - project: 'capella-addons/common/gitlab-libraries'
#    ref: 'master'
#    file: 'ci-steps.yml'

stages:
  - build-capella
  - deploy

cache:
  - key: $CI_COMMIT_SHA
    paths:
      - releng/org.polarsys.capella.cybersecurity.site/target/
      - releng/org.polarsys.capella.cybersecurity.target/target/
  - key: capella-cyber-m2
    paths:
      - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  ADDON_NAME: "Darc"  

build-capella:
  stage: build-capella
  image: gitlab.thalesdigital.io:5005/capella-addons/common/capella-invaders-docker/capella-invaders-ui-agent:0.72
  script:
    # generate TP
    - mvn clean verify -f releng/org.polarsys.capella.cybersecurity.target/pom.xml -DsettingsFileLocation=$MAVEN_SETTINGS -t ~/.m2/toolchains.xml
    
    # build and run tests
    - ~/.vnc/xstartup.sh &
    - mvn install -Dmaven.test.failure.ignore=true -Dtycho.localArtifacts=ignore -t ~/.m2/toolchains.xml
    - pkill Xvnc
  artifacts:
      when: always
      paths:
        - tests/org.polarsys.capella.cybersecurity.test/target/work/data/.metadata/*.log
        - releng/org.polarsys.capella.cybersecurity.target/workspace/.metadata/*.log
        - releng/org.polarsys.capella.cybersecurity.target/target/eclipserun-work/configuration/*.log
        - capella/configuration/*.log
      reports:
        junit:
          - tests/org.polarsys.capella.cybersecurity.test/target/surefire-reports/TEST-*.xml

Deploy:
  stage: deploy
  image: curlimages/curl 
  variables:
    CYBER_ARTIFACTORY_URL: https://artifactory.thalesdigital.io/artifactory/generic-internal/capella-invaders/
    RESOURCES_DIR: "releng/org.polarsys.capella.cybersecurity.site/target"
    DEPLOY_DIR: "Cybersecurity/nightly/$CI_COMMIT_BRANCH/$CI_PIPELINE_ID"
  artifacts:
    paths:
      - $RESOURCES_DIR/Darc-dropins*
      - $RESOURCES_DIR/Darc-updateSite*
  script:
    - DROPINS_FILE=$(find $RESOURCES_DIR -name Darc-dropins*)
    - UPDATE_SITE_FILE=$(find $RESOURCES_DIR -name Darc-updateSite*)
    - echo "Deploying $DROPINS_FILE..."
    - curl -k -H "X-JFrog-Art-Api:$ARTIFACTORY_KEY" -T $DROPINS_FILE $CYBER_ARTIFACTORY_URL$DEPLOY_DIR/
    - echo "Deploying $UPDATE_SITE_FILE..."
    - curl -k -H "X-JFrog-Art-Api:$ARTIFACTORY_KEY" -T $UPDATE_SITE_FILE $CYBER_ARTIFACTORY_URL$DEPLOY_DIR/
