include:
  - project: 'capella-addons/common/ci-templates'
    ref: 'main'
    file: 'basic-addon.yml'

stages:
  - build

variables:
  extends: .common_variables
  DEPLOY_DIR: "Cybersecurity/nightly/$CI_COMMIT_REF_NAME/$CI_PIPELINE_ID"
  ADDON: Darc
  RELENG_PATH: releng/org.polarsys.capella.cybersecurity.target
  UPDATE_DROPIN_PATHS: releng/org.polarsys.capella.cybersecurity.site

build:
  extends: .basic_addon_build
  stage: build
  before_script:
    - cp /home/jenkins/basicaddon.target-definition.target $RELENG_PATH/capella.target-definition.target