###################################################################
# Copyright © 2021 Thales Global Services SAS
#
# Licensed under the Thales Inner Source Software License:
# Version 1.2, InnerOpen - Distribution Controlled
#
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at https://gitlab.thalesdigital.io/Tiss-Organization/tiss-licenses
# See the License for the specific language governing permissions and limitations under the License.
###################################################################
stages:
  - download-capella
  - generate-target-platform
  - build
  - deploy

cache:
  key:
    $CI_PIPELINE_ID
  paths:
    - downloads/
    - releng/

.Download Capella:
  stage: download-capella
  image: curlimages/curl 
  variables:
    CAPELLA_URL_BASE: "https://download.eclipse.org/capella/core/products/nightly/master/"
  script:
    - mkdir -p downloads
    - html=$(curl -ks ${CAPELLA_URL_BASE})
    - ZIP_NAME_WIN=$(echo $html | sed -e 's/.*\(capella-.*-win32-win32-x86_64.zip\).*/\1/')
    - ZIP_NAME_LIN=$(echo $html | sed -e 's/.*\(capella-.*-linux-gtk-x86_64.tar.gz\).*/\1/')
    - CAPELLA_URL_WIN="$CAPELLA_URL_BASE/$ZIP_NAME_WIN"
    - CAPELLA_URL_LINUX="$CAPELLA_URL_BASE/$ZIP_NAME_LIN"
    - echo "Downloading $CAPELLA_URL_WIN ..."
    - curl -k -o downloads/capella-win.zip $CAPELLA_URL_WIN
    - echo "Downloading $CAPELLA_URL_LINUX ..."
    - curl -k -o downloads/capella.tar.gz $CAPELLA_URL_LINUX

Generate Target Platform:
  stage: generate-target-platform
  image: maven:3.6.1-jdk-8-alpine
  script:
    - mvn clean verify -f releng/org.polarsys.capella.cybersecurity.target/pom.xml 
    
Build and Package:
  stage: build
  image: adoptopenjdk/maven-openjdk11
  script:
    - mvn -Djacoco.skip=true -DjavaDocPhase=none clean package -f pom.xml

Deploy:
  stage: deploy
  image: curlimages/curl 
  variables:
    CYBER_ARTIFACTORY_URL: https://artifactory.thalesdigital.io/artifactory/generic-internal/capella-invaders/
    RESOURCES_DIR: "releng/org.polarsys.capella.cybersecurity.site/target"
    DEPLOY_DIR: "Cybersecurity/nightly/$CI_COMMIT_BRANCH/$CI_PIPELINE_ID"
  artifacts:
    paths:
      - $RESOURCES_DIR/Darc-dropins*
      - $RESOURCES_DIR/Darc-updateSite*
  script:
    - DROPINS_FILE=$(find $RESOURCES_DIR -name Darc-dropins*)
    - UPDATE_SITE_FILE=$(find $RESOURCES_DIR -name Darc-updateSite*)
    - echo "Deploying $DROPINS_FILE..."
    - curl -k -H "X-JFrog-Art-Api:$ARTIFACTORY_KEY" -T $DROPINS_FILE $CYBER_ARTIFACTORY_URL$DEPLOY_DIR/
    - echo "Deploying $UPDATE_SITE_FILE..."
    - curl -k -H "X-JFrog-Art-Api:$ARTIFACTORY_KEY" -T $UPDATE_SITE_FILE $CYBER_ARTIFACTORY_URL$DEPLOY_DIR/
