stages:
  - build

build:
  stage: build
  image: ${CI_REGISTRY}/capella-addons/common/capella-invaders-docker/capella-invaders-ui-agent:0.94

  variables:
    CAPELLA_ARTIFACTORY_URL: https://artifactory.thalesdigital.io/artifactory/generic-internal/capella-invaders/
    DEPLOY_DIR: "Cybersecurity/nightly/$CI_COMMIT_REF_NAME/$CI_PIPELINE_ID"

  script:
    # generate TP
    - mvn clean verify -f releng/org.polarsys.capella.cybersecurity.target/pom.xml -DsettingsFileLocation=$MAVEN_SETTINGS
    - cat releng/org.polarsys.capella.cybersecurity.target/capella.target-definition.target

    # build and run tests
    - ~/.vnc/xstartup.sh &
    - mvn -e install -f pom.xml -Dmaven.test.failure.ignore=true
    - pkill Xvnc

    # deploy
    - DROPINS_FILE=$(find "releng/org.polarsys.capella.cybersecurity.site/target" -name Darc-dropins*)
    - echo "Deploying $DROPINS_FILE..."
    - curl -k -H "X-JFrog-Art-Api:$ARTIFACTORY_TOKEN" -T $DROPINS_FILE $CAPELLA_ARTIFACTORY_URL$DEPLOY_DIR/

    - UPDATE_SITE_FILE=$(find "releng/org.polarsys.capella.cybersecurity.site/target" -name Darc-updateSite*)
    - echo "Deploying $UPDATE_SITE_FILE..."
    - curl -k -H "X-JFrog-Art-Api:$ARTIFACTORY_TOKEN" -T $UPDATE_SITE_FILE $CAPELLA_ARTIFACTORY_URL$DEPLOY_DIR/

  artifacts:
      when: always
      paths:
        - tests/org.polarsys.capella.cybersecurity.test/target/work/data/.metadata/*.log
        - releng/org.polarsys.capella.cybersecurity.target/workspace/.metadata/*.log
        - releng/org.polarsys.capella.cybersecurity.target/target/eclipserun-work/configuration/*.log
        - capella/configuration/*.log
      reports:
        junit:
          - tests/org.polarsys.capella.cybersecurity.test/target/surefire-reports/TEST-*.xml
